packages:
  - 'packages/*'
  - 'playground/*'
  - 'examples/*'


catalog:
  'vite': ^5.4.10
  'lwc': ^8.6.0
  '@lwc/engine-core': ^8.6.0
  '@lwc/engine-dom': ^8.6.0
  '@lwc/engine-server': ^8.6.0
  '@lwc/shared': ^8.6.0
  '@lwc/ssr-runtime': ^8.6.0
  '@lwc/synthetic-shadow': ^8.6.0
  '@lwc/wire-service': ^8.6.0
  '@lwc/rollup-plugin': ^8.6.0